## 2.3.1 strconv 包转换错误处理-总结

- **(1) `ErrRange` 表示值超过类型能表示的最大范围，如将 "128" 转为 int8。**
- **(2) `ErrSyntax` 表示语法错误，如将 "" 转为 int 类型会返回这个错误。**
- **(3) 报错时构造一个 *NumError* 类型的 *error* 对象返回。**
  - `Func string`  报错的函数
  - `Num string`  输入
  - `Err error`  错误
- **(4) 在包中通过`syntaxError`和`rangeError`函数构造 *NumError* 对象。**

## 2.3.1 strconv 包转换错误处理

介绍具体的转换之前，先看看 *strconv* 中的错误处理。

由于将字符串转为其他数据类型可能会出错，*strconv* 包定义了两个 *error* 类型的变量：*ErrRange* 和 *ErrSyntax*。其中，*ErrRange* 表示值超过了类型能表示的最大范围，比如将 "128" 转为 int8 就会返回这个错误；*ErrSyntax* 表示语法错误，比如将 "" 转为 int 类型会返回这个错误。

然而，在返回错误的时候，不是直接将上面的变量值返回，而是通过构造一个 *NumError* 类型的 *error* 对象返回。*NumError* 结构的定义如下：

```go
// A NumError records a failed conversion.
type NumError struct {
    Func string // the failing function (ParseBool, ParseInt, ParseUint, ParseFloat)
    Num  string // the input
    Err  error  // the reason the conversion failed (ErrRange, ErrSyntax)
}
```

可见，该结构记录了转换过程中发生的错误信息。该结构不仅包含了一个 *error* 类型的成员，记录具体的错误信息，而且它自己也实现了 *error* 接口：

```go
func (e *NumError) Error() string {
    return "strconv." + e.Func + ": " + "parsing " + Quote(e.Num) + ": " + e.Err.Error()
}
```

包的实现中，定义了两个便捷函数，用于构造 *NumError* 对象：

```go
func syntaxError(fn, str string) *NumError {
    return &NumError{fn, str, ErrSyntax}
}

func rangeError(fn, str string) *NumError {
    return &NumError{fn, str, ErrRange}
}
```

在遇到 *ErrSyntax* 或 *ErrRange* 错误时，通过上面的函数构造 *NumError* 对象。
